name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build:production
      working-directory: ./show-logger

    - name: Show Logger SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: '${{ secrets.SSH_USER }}'
        server: '${{ secrets.SSH_IP_ADDRESS }}'
        port: 22
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        local_path: './show-logger/dist/*'
        remote_path: '/oaprojects/show-logger'

    
